# Generated by Django 4.2 on 2023-04-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="uid",
            field=models.CharField(
                db_index=True,
                default="6NRXRTWYVMDVGLXI",
                editable=False,
                max_length=16,
                unique=True,
                verbose_name="Product UID",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="uid",
            field=models.CharField(
                db_index=True,
                default="6NRXRTWYVMDVGLXI",
                editable=False,
                max_length=16,
                unique=True,
                verbose_name="Product UID",
            ),
        ),
        migrations.AlterField(
            model_name="productinventory",
            name="uid",
            field=models.CharField(
                db_index=True,
                default="VTLBZCIRKBP5PTOS",
                editable=False,
                max_length=16,
                unique=True,
                verbose_name="Product Inventory UID",
            ),
        ),
    ]
