# Generated by Django 4.2 on 2023-04-26 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="uid",
            field=models.CharField(
                db_index=True,
                default="XXIRZGEB7SZ0B1LA",
                editable=False,
                max_length=16,
                unique=True,
                verbose_name="Product UID",
            ),
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default="EZTQZSCBT3VAJXDM",
                        editable=False,
                        max_length=16,
                        unique=True,
                        verbose_name="Brand UID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, null=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="brands",
                        verbose_name="Brand Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brands",
                        to="inventory.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(related_name="brands", to="inventory.tag"),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
            },
        ),
    ]
