# Generated by Django 4.2 on 2023-04-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_product_uid_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, null=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Product Attribute",
                "verbose_name_plural": "Product Attributes",
            },
        ),
        migrations.AlterField(
            model_name="brand",
            name="uid",
            field=models.CharField(
                db_index=True,
                default="PEE6TINI7JEJU0TZ",
                editable=False,
                max_length=16,
                unique=True,
                verbose_name="Brand UID",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="uid",
            field=models.CharField(
                db_index=True,
                default="SUWAB1Q7SOEI8YK9",
                editable=False,
                max_length=16,
                unique=True,
                verbose_name="Product UID",
            ),
        ),
    ]
